### ISSUE TITLE
app: 404: Not Found

### ISSUE THREAD

**Issue by RameshGhk** [Stranger6667/schemathesis-example#2]
Hi there,
I have set up the local env to run the app.
In my pycharm it show app is running at 
`======== Running on http://0.0.0.0:8888 ========
(Press CTRL+C to quit)
`
But When I try to access the link http://localhost:8888, it throws error page  not found..
Any idea/help will be a great ..
Thanks in advance

Regards,
Ramesh

**Comment by Stranger6667** [comment]
Hi!

It looks like I did not give a proper app description in the documentation - surely will improve it soon :)

This is expected behavior - there are only two endpoints and a schema:

- `GET /bookings/{booking_id}` - get a booking by id
- `POST /bookings/` - create a new booking

The schema is available at `/schema.yaml`. Other paths are expected to return 404.

More information about this app is available in my article - https://dygalo.dev/blog/schemathesis-property-based-testing-for-api-schemas/

This repo was written as a part of this article to show off Schemathesis capabilities.
Let me know if this sheds enough light on the app behavior :)

**Comment by RameshGhk** [comment]
@Stranger6667 Yes, I can access schema and run schema as well. You can close this issue.
Thanks

**Comment by Stranger6667** [comment]
@RameshGhk , you are very welcome :)
